-- Generated by Python

local icons = {
    Accessory = {
        ImageRectPosition = Vector2.new(0, 0),
        _Size = Vector2.new(32, 32),
        },
    Accoutrement = {
        ImageRectPosition = Vector2.new(32, 0),
        _Size = Vector2.new(32, 32),
        },
    Actor = {
        ImageRectPosition = Vector2.new(64, 0),
        _Size = Vector2.new(32, 32),
        },
    AdGui = {
        ImageRectPosition = Vector2.new(96, 0),
        _Size = Vector2.new(32, 32),
        },
    AdPortal = {
        ImageRectPosition = Vector2.new(128, 0),
        _Size = Vector2.new(32, 32),
        },
    AdService = {
        ImageRectPosition = Vector2.new(160, 0),
        _Size = Vector2.new(32, 32),
        },
    AdvancedDragger = {
        ImageRectPosition = Vector2.new(192, 0),
        _Size = Vector2.new(32, 32),
        },
    AirController = {
        ImageRectPosition = Vector2.new(224, 0),
        _Size = Vector2.new(32, 32),
        },
    AlignOrientation = {
        ImageRectPosition = Vector2.new(256, 0),
        _Size = Vector2.new(32, 32),
        },
    AlignPosition = {
        ImageRectPosition = Vector2.new(288, 0),
        _Size = Vector2.new(32, 32),
        },
    AnalysticsService = {
        ImageRectPosition = Vector2.new(320, 0),
        _Size = Vector2.new(32, 32),
        },
    AnalysticsSettings = {
        ImageRectPosition = Vector2.new(352, 0),
        _Size = Vector2.new(32, 32),
        },
    AnalyticsService = {
        ImageRectPosition = Vector2.new(384, 0),
        _Size = Vector2.new(32, 32),
        },
    AngularVelocity = {
        ImageRectPosition = Vector2.new(416, 0),
        _Size = Vector2.new(32, 32),
        },
    Animation = {
        ImageRectPosition = Vector2.new(448, 0),
        _Size = Vector2.new(32, 32),
        },
    AnimationClip = {
        ImageRectPosition = Vector2.new(480, 0),
        _Size = Vector2.new(32, 32),
        },
    AnimationClipProvider = {
        ImageRectPosition = Vector2.new(512, 0),
        _Size = Vector2.new(32, 32),
        },
    AnimationController = {
        ImageRectPosition = Vector2.new(544, 0),
        _Size = Vector2.new(32, 32),
        },
    AnimationFromVideoCreatorService = {
        ImageRectPosition = Vector2.new(576, 0),
        _Size = Vector2.new(32, 32),
        },
    AnimationFromVideoCreatorStudioService = {
        ImageRectPosition = Vector2.new(608, 0),
        _Size = Vector2.new(32, 32),
        },
    AnimationRigData = {
        ImageRectPosition = Vector2.new(640, 0),
        _Size = Vector2.new(32, 32),
        },
    AnimationStreamTrack = {
        ImageRectPosition = Vector2.new(672, 0),
        _Size = Vector2.new(32, 32),
        },
    AnimationTrack = {
        ImageRectPosition = Vector2.new(704, 0),
        _Size = Vector2.new(32, 32),
        },
    Animator = {
        ImageRectPosition = Vector2.new(736, 0),
        _Size = Vector2.new(32, 32),
        },
    AppStorageService = {
        ImageRectPosition = Vector2.new(0, 32),
        _Size = Vector2.new(32, 32),
        },
    AppUpdateService = {
        ImageRectPosition = Vector2.new(32, 32),
        _Size = Vector2.new(32, 32),
        },
    ArcHandles = {
        ImageRectPosition = Vector2.new(64, 32),
        _Size = Vector2.new(32, 32),
        },
    AssetCounterService = {
        ImageRectPosition = Vector2.new(96, 32),
        _Size = Vector2.new(32, 32),
        },
    AssetDeliveryProxy = {
        ImageRectPosition = Vector2.new(128, 32),
        _Size = Vector2.new(32, 32),
        },
    AssetImportService = {
        ImageRectPosition = Vector2.new(160, 32),
        _Size = Vector2.new(32, 32),
        },
    AssetImportSession = {
        ImageRectPosition = Vector2.new(192, 32),
        _Size = Vector2.new(32, 32),
        },
    AssetManagerService = {
        ImageRectPosition = Vector2.new(224, 32),
        _Size = Vector2.new(32, 32),
        },
    AssetService = {
        ImageRectPosition = Vector2.new(256, 32),
        _Size = Vector2.new(32, 32),
        },
    AssetSoundEffect = {
        ImageRectPosition = Vector2.new(288, 32),
        _Size = Vector2.new(32, 32),
        },
    Atmosphere = {
        ImageRectPosition = Vector2.new(320, 32),
        _Size = Vector2.new(32, 32),
        },
    Attachment = {
        ImageRectPosition = Vector2.new(352, 32),
        _Size = Vector2.new(32, 32),
        },
    AvatarEditorService = {
        ImageRectPosition = Vector2.new(384, 32),
        _Size = Vector2.new(32, 32),
        },
    AvatarImportService = {
        ImageRectPosition = Vector2.new(416, 32),
        _Size = Vector2.new(32, 32),
        },
    Backpack = {
        ImageRectPosition = Vector2.new(448, 32),
        _Size = Vector2.new(32, 32),
        },
    BackpackItem = {
        ImageRectPosition = Vector2.new(480, 32),
        _Size = Vector2.new(32, 32),
        },
    BadgeService = {
        ImageRectPosition = Vector2.new(512, 32),
        _Size = Vector2.new(32, 32),
        },
    BallSocketConstraint = {
        ImageRectPosition = Vector2.new(544, 32),
        _Size = Vector2.new(32, 32),
        },
    BasePart = {
        ImageRectPosition = Vector2.new(576, 32),
        _Size = Vector2.new(32, 32),
        },
    BasePlayerGui = {
        ImageRectPosition = Vector2.new(608, 32),
        _Size = Vector2.new(32, 32),
        },
    BaseScript = {
        ImageRectPosition = Vector2.new(640, 32),
        _Size = Vector2.new(32, 32),
        },
    BaseWrap = {
        ImageRectPosition = Vector2.new(672, 32),
        _Size = Vector2.new(32, 32),
        },
    Beam = {
        ImageRectPosition = Vector2.new(704, 32),
        _Size = Vector2.new(32, 32),
        },
    BevelMesh = {
        ImageRectPosition = Vector2.new(736, 32),
        _Size = Vector2.new(32, 32),
        },
    BillboardGui = {
        ImageRectPosition = Vector2.new(0, 64),
        _Size = Vector2.new(32, 32),
        },
    BinaryStringValue = {
        ImageRectPosition = Vector2.new(32, 64),
        _Size = Vector2.new(32, 32),
        },
    BindableEvent = {
        ImageRectPosition = Vector2.new(64, 64),
        _Size = Vector2.new(32, 32),
        },
    BindableFunction = {
        ImageRectPosition = Vector2.new(96, 64),
        _Size = Vector2.new(32, 32),
        },
    BlockMesh = {
        ImageRectPosition = Vector2.new(128, 64),
        _Size = Vector2.new(32, 32),
        },
    BloomEffect = {
        ImageRectPosition = Vector2.new(160, 64),
        _Size = Vector2.new(32, 32),
        },
    BlurEffect = {
        ImageRectPosition = Vector2.new(192, 64),
        _Size = Vector2.new(32, 32),
        },
    BodyAngularVelocity = {
        ImageRectPosition = Vector2.new(224, 64),
        _Size = Vector2.new(32, 32),
        },
    BodyColors = {
        ImageRectPosition = Vector2.new(256, 64),
        _Size = Vector2.new(32, 32),
        },
    BodyForce = {
        ImageRectPosition = Vector2.new(288, 64),
        _Size = Vector2.new(32, 32),
        },
    BodyGyro = {
        ImageRectPosition = Vector2.new(320, 64),
        _Size = Vector2.new(32, 32),
        },
    BodyMover = {
        ImageRectPosition = Vector2.new(352, 64),
        _Size = Vector2.new(32, 32),
        },
    BodyPosition = {
        ImageRectPosition = Vector2.new(384, 64),
        _Size = Vector2.new(32, 32),
        },
    BodyThrust = {
        ImageRectPosition = Vector2.new(416, 64),
        _Size = Vector2.new(32, 32),
        },
    BodyVelocity = {
        ImageRectPosition = Vector2.new(448, 64),
        _Size = Vector2.new(32, 32),
        },
    Bone = {
        ImageRectPosition = Vector2.new(480, 64),
        _Size = Vector2.new(32, 32),
        },
    BoolValue = {
        ImageRectPosition = Vector2.new(512, 64),
        _Size = Vector2.new(32, 32),
        },
    BoxHandleAdornment = {
        ImageRectPosition = Vector2.new(544, 64),
        _Size = Vector2.new(32, 32),
        },
    Breakpoint = {
        ImageRectPosition = Vector2.new(576, 64),
        _Size = Vector2.new(32, 32),
        },
    BreakpointManager = {
        ImageRectPosition = Vector2.new(608, 64),
        _Size = Vector2.new(32, 32),
        },
    BrickColorValue = {
        ImageRectPosition = Vector2.new(640, 64),
        _Size = Vector2.new(32, 32),
        },
    BrowserService = {
        ImageRectPosition = Vector2.new(672, 64),
        _Size = Vector2.new(32, 32),
        },
    BubbleChatConfiguration = {
        ImageRectPosition = Vector2.new(704, 64),
        _Size = Vector2.new(32, 32),
        },
    BulkImportService = {
        ImageRectPosition = Vector2.new(736, 64),
        _Size = Vector2.new(32, 32),
        },
    CacheableContentProvider = {
        ImageRectPosition = Vector2.new(0, 96),
        _Size = Vector2.new(32, 32),
        },
    CalloutService = {
        ImageRectPosition = Vector2.new(32, 96),
        _Size = Vector2.new(32, 32),
        },
    Camera = {
        ImageRectPosition = Vector2.new(64, 96),
        _Size = Vector2.new(32, 32),
        },
    CanvasGroup = {
        ImageRectPosition = Vector2.new(96, 96),
        _Size = Vector2.new(32, 32),
        },
    CatalogPages = {
        ImageRectPosition = Vector2.new(128, 96),
        _Size = Vector2.new(32, 32),
        },
    CFrameValue = {
        ImageRectPosition = Vector2.new(160, 96),
        _Size = Vector2.new(32, 32),
        },
    ChangeHistoryService = {
        ImageRectPosition = Vector2.new(192, 96),
        _Size = Vector2.new(32, 32),
        },
    ChannelSelectorSoundEffect = {
        ImageRectPosition = Vector2.new(224, 96),
        _Size = Vector2.new(32, 32),
        },
    CharacterAppearance = {
        ImageRectPosition = Vector2.new(256, 96),
        _Size = Vector2.new(32, 32),
        },
    CharacterMesh = {
        ImageRectPosition = Vector2.new(288, 96),
        _Size = Vector2.new(32, 32),
        },
    Chat = {
        ImageRectPosition = Vector2.new(320, 96),
        _Size = Vector2.new(32, 32),
        },
    ChatInputBarConfiguration = {
        ImageRectPosition = Vector2.new(352, 96),
        _Size = Vector2.new(32, 32),
        },
    ChatWindowConfiguration = {
        ImageRectPosition = Vector2.new(384, 96),
        _Size = Vector2.new(32, 32),
        },
    ChorusSoundEffect = {
        ImageRectPosition = Vector2.new(416, 96),
        _Size = Vector2.new(32, 32),
        },
    ClickDetector = {
        ImageRectPosition = Vector2.new(448, 96),
        _Size = Vector2.new(32, 32),
        },
    ClientReplicator = {
        ImageRectPosition = Vector2.new(480, 96),
        _Size = Vector2.new(32, 32),
        },
    ClimbController = {
        ImageRectPosition = Vector2.new(512, 96),
        _Size = Vector2.new(32, 32),
        },
    Clothing = {
        ImageRectPosition = Vector2.new(544, 96),
        _Size = Vector2.new(32, 32),
        },
    Clouds = {
        ImageRectPosition = Vector2.new(576, 96),
        _Size = Vector2.new(32, 32),
        },
    ClusterPacketCache = {
        ImageRectPosition = Vector2.new(608, 96),
        _Size = Vector2.new(32, 32),
        },
    CollectionService = {
        ImageRectPosition = Vector2.new(640, 96),
        _Size = Vector2.new(32, 32),
        },
    Color3Value = {
        ImageRectPosition = Vector2.new(672, 96),
        _Size = Vector2.new(32, 32),
        },
    ColorCorrectionEffect = {
        ImageRectPosition = Vector2.new(704, 96),
        _Size = Vector2.new(32, 32),
        },
    CommandInstance = {
        ImageRectPosition = Vector2.new(736, 96),
        _Size = Vector2.new(32, 32),
        },
    CommandService = {
        ImageRectPosition = Vector2.new(0, 128),
        _Size = Vector2.new(32, 32),
        },
    CompressorSoundEffect = {
        ImageRectPosition = Vector2.new(32, 128),
        _Size = Vector2.new(32, 32),
        },
    ConeHandleAdornment = {
        ImageRectPosition = Vector2.new(64, 128),
        _Size = Vector2.new(32, 32),
        },
    Configuration = {
        ImageRectPosition = Vector2.new(96, 128),
        _Size = Vector2.new(32, 32),
        },
    ConfigureServerService = {
        ImageRectPosition = Vector2.new(128, 128),
        _Size = Vector2.new(32, 32),
        },
    Constraint = {
        ImageRectPosition = Vector2.new(160, 128),
        _Size = Vector2.new(32, 32),
        },
    ContentProvider = {
        ImageRectPosition = Vector2.new(192, 128),
        _Size = Vector2.new(32, 32),
        },
    ContextActionService = {
        ImageRectPosition = Vector2.new(224, 128),
        _Size = Vector2.new(32, 32),
        },
    Controller = {
        ImageRectPosition = Vector2.new(256, 128),
        _Size = Vector2.new(32, 32),
        },
    ControllerBase = {
        ImageRectPosition = Vector2.new(288, 128),
        _Size = Vector2.new(32, 32),
        },
    ControllerManager = {
        ImageRectPosition = Vector2.new(320, 128),
        _Size = Vector2.new(32, 32),
        },
    ControllerService = {
        ImageRectPosition = Vector2.new(352, 128),
        _Size = Vector2.new(32, 32),
        },
    CookiesService = {
        ImageRectPosition = Vector2.new(384, 128),
        _Size = Vector2.new(32, 32),
        },
    CoreGui = {
        ImageRectPosition = Vector2.new(416, 128),
        _Size = Vector2.new(32, 32),
        },
    CorePackages = {
        ImageRectPosition = Vector2.new(448, 128),
        _Size = Vector2.new(32, 32),
        },
    CoreScript = {
        ImageRectPosition = Vector2.new(480, 128),
        _Size = Vector2.new(32, 32),
        },
    CoreScriptSyncService = {
        ImageRectPosition = Vector2.new(512, 128),
        _Size = Vector2.new(32, 32),
        },
    CornerWedgePart = {
        ImageRectPosition = Vector2.new(544, 128),
        _Size = Vector2.new(32, 32),
        },
    CrossDMScriptChangeListener = {
        ImageRectPosition = Vector2.new(576, 128),
        _Size = Vector2.new(32, 32),
        },
    CSGDictionaryService = {
        ImageRectPosition = Vector2.new(608, 128),
        _Size = Vector2.new(32, 32),
        },
    CurveAnimation = {
        ImageRectPosition = Vector2.new(640, 128),
        _Size = Vector2.new(32, 32),
        },
    CustomEvent = {
        ImageRectPosition = Vector2.new(672, 128),
        _Size = Vector2.new(32, 32),
        },
    CustomEventReceiver = {
        ImageRectPosition = Vector2.new(704, 128),
        _Size = Vector2.new(32, 32),
        },
    CustomSoundEffect = {
        ImageRectPosition = Vector2.new(736, 128),
        _Size = Vector2.new(32, 32),
        },
    CylinderHandleAdornment = {
        ImageRectPosition = Vector2.new(0, 160),
        _Size = Vector2.new(32, 32),
        },
    CylinderMesh = {
        ImageRectPosition = Vector2.new(32, 160),
        _Size = Vector2.new(32, 32),
        },
    CylindricalConstraint = {
        ImageRectPosition = Vector2.new(64, 160),
        _Size = Vector2.new(32, 32),
        },
    DataModel = {
        ImageRectPosition = Vector2.new(96, 160),
        _Size = Vector2.new(32, 32),
        },
    DataModelMesh = {
        ImageRectPosition = Vector2.new(128, 160),
        _Size = Vector2.new(32, 32),
        },
    DataModelPatchService = {
        ImageRectPosition = Vector2.new(160, 160),
        _Size = Vector2.new(32, 32),
        },
    DataModelSession = {
        ImageRectPosition = Vector2.new(192, 160),
        _Size = Vector2.new(32, 32),
        },
    DataStore = {
        ImageRectPosition = Vector2.new(224, 160),
        _Size = Vector2.new(32, 32),
        },
    DataStoreIncrementOptions = {
        ImageRectPosition = Vector2.new(256, 160),
        _Size = Vector2.new(32, 32),
        },
    DataStoreInfo = {
        ImageRectPosition = Vector2.new(288, 160),
        _Size = Vector2.new(32, 32),
        },
    DataStoreKey = {
        ImageRectPosition = Vector2.new(320, 160),
        _Size = Vector2.new(32, 32),
        },
    Debris = {
        ImageRectPosition = Vector2.new(352, 160),
        _Size = Vector2.new(32, 32),
        },
    DataStoreKeyInfo = {
        ImageRectPosition = Vector2.new(384, 160),
        _Size = Vector2.new(32, 32),
        },
    DataStoreListingPages = {
        ImageRectPosition = Vector2.new(416, 160),
        _Size = Vector2.new(32, 32),
        },
    DataStorePages = {
        ImageRectPosition = Vector2.new(448, 160),
        _Size = Vector2.new(32, 32),
        },
    DataStoreService = {
        ImageRectPosition = Vector2.new(480, 160),
        _Size = Vector2.new(32, 32),
        },
    DataStoreSetOptions = {
        ImageRectPosition = Vector2.new(512, 160),
        _Size = Vector2.new(32, 32),
        },
    DataStoreVersionPages = {
        ImageRectPosition = Vector2.new(544, 160),
        _Size = Vector2.new(32, 32),
        },
    DebuggablePluginWatcher = {
        ImageRectPosition = Vector2.new(576, 160),
        _Size = Vector2.new(32, 32),
        },
    DebuggerConnection = {
        ImageRectPosition = Vector2.new(608, 160),
        _Size = Vector2.new(32, 32),
        },
    DebuggerLuaResponse = {
        ImageRectPosition = Vector2.new(640, 160),
        _Size = Vector2.new(32, 32),
        },
    DebuggerManager = {
        ImageRectPosition = Vector2.new(672, 160),
        _Size = Vector2.new(32, 32),
        },
    DebuggerUIService = {
        ImageRectPosition = Vector2.new(704, 160),
        _Size = Vector2.new(32, 32),
        },
    Decal = {
        ImageRectPosition = Vector2.new(736, 160),
        _Size = Vector2.new(32, 32),
        },
    DepthOfFieldEffect = {
        ImageRectPosition = Vector2.new(0, 192),
        _Size = Vector2.new(32, 32),
        },
    DeviceIdService = {
        ImageRectPosition = Vector2.new(32, 192),
        _Size = Vector2.new(32, 32),
        },
    DockWidgetPluginGui = {
        ImageRectPosition = Vector2.new(64, 192),
        _Size = Vector2.new(32, 32),
        },
    DoubleConstrainedValue = {
        ImageRectPosition = Vector2.new(96, 192),
        _Size = Vector2.new(32, 32),
        },
    DraftsService = {
        ImageRectPosition = Vector2.new(128, 192),
        _Size = Vector2.new(32, 32),
        },
    Dragger = {
        ImageRectPosition = Vector2.new(160, 192),
        _Size = Vector2.new(32, 32),
        },
    DynamicRotate = {
        ImageRectPosition = Vector2.new(192, 192),
        _Size = Vector2.new(32, 32),
        },
    EchoSoundEffect = {
        ImageRectPosition = Vector2.new(224, 192),
        _Size = Vector2.new(32, 32),
        },
    EulerRotationCurve = {
        ImageRectPosition = Vector2.new(256, 192),
        _Size = Vector2.new(32, 32),
        },
    EventIngestService = {
        ImageRectPosition = Vector2.new(288, 192),
        _Size = Vector2.new(32, 32),
        },
    FaceInstance = {
        ImageRectPosition = Vector2.new(320, 192),
        _Size = Vector2.new(32, 32),
        },
    FacialAnimationStreamingService = {
        ImageRectPosition = Vector2.new(352, 192),
        _Size = Vector2.new(32, 32),
        },
    Feature = {
        ImageRectPosition = Vector2.new(384, 192),
        _Size = Vector2.new(32, 32),
        },
    File = {
        ImageRectPosition = Vector2.new(416, 192),
        _Size = Vector2.new(32, 32),
        },
    FileMesh = {
        ImageRectPosition = Vector2.new(448, 192),
        _Size = Vector2.new(32, 32),
        },
    Fire = {
        ImageRectPosition = Vector2.new(480, 192),
        _Size = Vector2.new(32, 32),
        },
    Flag = {
        ImageRectPosition = Vector2.new(512, 192),
        _Size = Vector2.new(32, 32),
        },
    FlagStandService = {
        ImageRectPosition = Vector2.new(544, 192),
        _Size = Vector2.new(32, 32),
        },
    FlangeSoundEffect = {
        ImageRectPosition = Vector2.new(576, 192),
        _Size = Vector2.new(32, 32),
        },
    FloatCurve = {
        ImageRectPosition = Vector2.new(608, 192),
        _Size = Vector2.new(32, 32),
        },
    FlyweightService = {
        ImageRectPosition = Vector2.new(640, 192),
        _Size = Vector2.new(32, 32),
        },
    Folder = {
        ImageRectPosition = Vector2.new(672, 192),
        _Size = Vector2.new(32, 32),
        },
    ForceField = {
        ImageRectPosition = Vector2.new(704, 192),
        _Size = Vector2.new(32, 32),
        },
    Frame = {
        ImageRectPosition = Vector2.new(736, 192),
        _Size = Vector2.new(32, 32),
        },
    FriendService = {
        ImageRectPosition = Vector2.new(0, 224),
        _Size = Vector2.new(32, 32),
        },
    GameSettings = {
        ImageRectPosition = Vector2.new(32, 224),
        _Size = Vector2.new(32, 32),
        },
    GenericSettings = {
        ImageRectPosition = Vector2.new(64, 224),
        _Size = Vector2.new(32, 32),
        },
    Geometry = {
        ImageRectPosition = Vector2.new(96, 224),
        _Size = Vector2.new(32, 32),
        },
    GlobalDataStore = {
        ImageRectPosition = Vector2.new(128, 224),
        _Size = Vector2.new(32, 32),
        },
    Glue = {
        ImageRectPosition = Vector2.new(160, 224),
        _Size = Vector2.new(32, 32),
        },
    GuidRegistryService = {
        ImageRectPosition = Vector2.new(192, 224),
        _Size = Vector2.new(32, 32),
        },
    GuiObject = {
        ImageRectPosition = Vector2.new(224, 224),
        _Size = Vector2.new(32, 32),
        },
    GuiService = {
        ImageRectPosition = Vector2.new(256, 224),
        _Size = Vector2.new(32, 32),
        },
    HandlesBase = {
        ImageRectPosition = Vector2.new(288, 224),
        _Size = Vector2.new(32, 32),
        },
    HeightmapImporterService = {
        ImageRectPosition = Vector2.new(320, 224),
        _Size = Vector2.new(32, 32),
        },
    Hopper = {
        ImageRectPosition = Vector2.new(352, 224),
        _Size = Vector2.new(32, 32),
        },
    HopperBin = {
        ImageRectPosition = Vector2.new(384, 224),
        _Size = Vector2.new(32, 32),
        },
    HSRDataContentProvider = {
        ImageRectPosition = Vector2.new(416, 224),
        _Size = Vector2.new(32, 32),
        },
    HttpRequest = {
        ImageRectPosition = Vector2.new(448, 224),
        _Size = Vector2.new(32, 32),
        },
    HumanoidController = {
        ImageRectPosition = Vector2.new(480, 224),
        _Size = Vector2.new(32, 32),
        },
    HumanoidDescription = {
        ImageRectPosition = Vector2.new(512, 224),
        _Size = Vector2.new(32, 32),
        },
    IKControl = {
        ImageRectPosition = Vector2.new(544, 224),
        _Size = Vector2.new(32, 32),
        },
    ImageButton = {
        ImageRectPosition = Vector2.new(576, 224),
        _Size = Vector2.new(32, 32),
        },
    ImageHandleAdornment = {
        ImageRectPosition = Vector2.new(608, 224),
        _Size = Vector2.new(32, 32),
        },
    ImageLabel = {
        ImageRectPosition = Vector2.new(640, 224),
        _Size = Vector2.new(32, 32),
        },
    ImporterGroupSettings = {
        ImageRectPosition = Vector2.new(672, 224),
        _Size = Vector2.new(32, 32),
        },
    ImporterJointSettings = {
        ImageRectPosition = Vector2.new(704, 224),
        _Size = Vector2.new(32, 32),
        },
    ImporterMaterialSettings = {
        ImageRectPosition = Vector2.new(736, 224),
        _Size = Vector2.new(32, 32),
        },
    ImporterMeshSettings = {
        ImageRectPosition = Vector2.new(0, 256),
        _Size = Vector2.new(32, 32),
        },
    ImporterRootSettings = {
        ImageRectPosition = Vector2.new(32, 256),
        _Size = Vector2.new(32, 32),
        },
    IncrementalPatchBuilder = {
        ImageRectPosition = Vector2.new(64, 256),
        _Size = Vector2.new(32, 32),
        },
    InsertService = {
        ImageRectPosition = Vector2.new(96, 256),
        _Size = Vector2.new(32, 32),
        },
    InstanceAdornment = {
        ImageRectPosition = Vector2.new(128, 256),
        _Size = Vector2.new(32, 32),
        },
    IXPService = {
        ImageRectPosition = Vector2.new(160, 256),
        _Size = Vector2.new(32, 32),
        },
    JointsService = {
        ImageRectPosition = Vector2.new(192, 256),
        _Size = Vector2.new(32, 32),
        },
    KeyboardService = {
        ImageRectPosition = Vector2.new(224, 256),
        _Size = Vector2.new(32, 32),
        },
    KeyframeSequence = {
        ImageRectPosition = Vector2.new(256, 256),
        _Size = Vector2.new(32, 32),
        },
    LanguageService = {
        ImageRectPosition = Vector2.new(288, 256),
        _Size = Vector2.new(32, 32),
        },
    LayerCollector = {
        ImageRectPosition = Vector2.new(320, 256),
        _Size = Vector2.new(32, 32),
        },
    Lighting = {
        ImageRectPosition = Vector2.new(352, 256),
        _Size = Vector2.new(32, 32),
        },
    LinearVelocity = {
        ImageRectPosition = Vector2.new(384, 256),
        _Size = Vector2.new(32, 32),
        },
    LineHandleAdornment = {
        ImageRectPosition = Vector2.new(416, 256),
        _Size = Vector2.new(32, 32),
        },
    LocalizationService = {
        ImageRectPosition = Vector2.new(448, 256),
        _Size = Vector2.new(32, 32),
        },
    LocalizationTable = {
        ImageRectPosition = Vector2.new(480, 256),
        _Size = Vector2.new(32, 32),
        },
    LocalScript = {
        ImageRectPosition = Vector2.new(512, 256),
        _Size = Vector2.new(32, 32),
        },
    LSPFileSyncService = {
        ImageRectPosition = Vector2.new(544, 256),
        _Size = Vector2.new(32, 32),
        },
    LuauScriptAnalyzerService = {
        ImageRectPosition = Vector2.new(576, 256),
        _Size = Vector2.new(32, 32),
        },
    LuaWebService = {
        ImageRectPosition = Vector2.new(608, 256),
        _Size = Vector2.new(32, 32),
        },
    ManualWeld = {
        ImageRectPosition = Vector2.new(640, 256),
        _Size = Vector2.new(32, 32),
        },
    MarkerCurve = {
        ImageRectPosition = Vector2.new(672, 256),
        _Size = Vector2.new(32, 32),
        },
    MaterialVariant = {
        ImageRectPosition = Vector2.new(704, 256),
        _Size = Vector2.new(32, 32),
        },
    MemStorageConnection = {
        ImageRectPosition = Vector2.new(736, 256),
        _Size = Vector2.new(32, 32),
        },
    MeshPart = {
        ImageRectPosition = Vector2.new(0, 288),
        _Size = Vector2.new(32, 32),
        },
    Message = {
        ImageRectPosition = Vector2.new(32, 288),
        _Size = Vector2.new(32, 32),
        },
    MessagingService = {
        ImageRectPosition = Vector2.new(64, 288),
        _Size = Vector2.new(32, 32),
        },
    MetaBreakpointManager = {
        ImageRectPosition = Vector2.new(96, 288),
        _Size = Vector2.new(32, 32),
        },
    ModuleScript = {
        ImageRectPosition = Vector2.new(128, 288),
        _Size = Vector2.new(32, 32),
        },
    Motor = {
        ImageRectPosition = Vector2.new(160, 288),
        _Size = Vector2.new(32, 32),
        },
    Motor6D = {
        ImageRectPosition = Vector2.new(192, 288),
        _Size = Vector2.new(32, 32),
        },
    MotorFeature = {
        ImageRectPosition = Vector2.new(224, 288),
        _Size = Vector2.new(32, 32),
        },
    Mouse = {
        ImageRectPosition = Vector2.new(256, 288),
        _Size = Vector2.new(32, 32),
        },
    MultipleDocumentInterfaceInstance = {
        ImageRectPosition = Vector2.new(288, 288),
        _Size = Vector2.new(32, 32),
        },
    NegateOperation = {
        ImageRectPosition = Vector2.new(320, 288),
        _Size = Vector2.new(32, 32),
        },
    NetworkClient = {
        ImageRectPosition = Vector2.new(352, 288),
        _Size = Vector2.new(32, 32),
        },
    NetworkPeer = {
        ImageRectPosition = Vector2.new(384, 288),
        _Size = Vector2.new(32, 32),
        },
    NetworkSettings = {
        ImageRectPosition = Vector2.new(416, 288),
        _Size = Vector2.new(32, 32),
        },
    NoCollisionConstraint = {
        ImageRectPosition = Vector2.new(448, 288),
        _Size = Vector2.new(32, 32),
        },
    NonReplicatedCSGDictionaryService = {
        ImageRectPosition = Vector2.new(480, 288),
        _Size = Vector2.new(32, 32),
        },
    NotificationService = {
        ImageRectPosition = Vector2.new(512, 288),
        _Size = Vector2.new(32, 32),
        },
    NumberPose = {
        ImageRectPosition = Vector2.new(544, 288),
        _Size = Vector2.new(32, 32),
        },
    NumberValue = {
        ImageRectPosition = Vector2.new(576, 288),
        _Size = Vector2.new(32, 32),
        },
    OrderedDataStore = {
        ImageRectPosition = Vector2.new(608, 288),
        _Size = Vector2.new(32, 32),
        },
    OutfitPages = {
        ImageRectPosition = Vector2.new(640, 288),
        _Size = Vector2.new(32, 32),
        },
    PackageLink = {
        ImageRectPosition = Vector2.new(672, 288),
        _Size = Vector2.new(32, 32),
        },
    PackageUIService = {
        ImageRectPosition = Vector2.new(704, 288),
        _Size = Vector2.new(32, 32),
        },
    Pants = {
        ImageRectPosition = Vector2.new(736, 288),
        _Size = Vector2.new(32, 32),
        },
    ParticleEmitter = {
        ImageRectPosition = Vector2.new(0, 320),
        _Size = Vector2.new(32, 32),
        },
    PartOperation = {
        ImageRectPosition = Vector2.new(32, 320),
        _Size = Vector2.new(32, 32),
        },
    PatchMapping = {
        ImageRectPosition = Vector2.new(64, 320),
        _Size = Vector2.new(32, 32),
        },
    PathfindingLink = {
        ImageRectPosition = Vector2.new(96, 320),
        _Size = Vector2.new(32, 32),
        },
    PathfindingService = {
        ImageRectPosition = Vector2.new(128, 320),
        _Size = Vector2.new(32, 32),
        },
    PausedState = {
        ImageRectPosition = Vector2.new(160, 320),
        _Size = Vector2.new(32, 32),
        },
    PausedStateBreakpoint = {
        ImageRectPosition = Vector2.new(192, 320),
        _Size = Vector2.new(32, 32),
        },
    PausedStateException = {
        ImageRectPosition = Vector2.new(224, 320),
        _Size = Vector2.new(32, 32),
        },
    PermissionsService = {
        ImageRectPosition = Vector2.new(256, 320),
        _Size = Vector2.new(32, 32),
        },
    Players = {
        ImageRectPosition = Vector2.new(288, 320),
        _Size = Vector2.new(32, 32),
        },
    PlayerScripts = {
        ImageRectPosition = Vector2.new(320, 320),
        _Size = Vector2.new(32, 32),
        },
    Plugin = {
        ImageRectPosition = Vector2.new(352, 320),
        _Size = Vector2.new(32, 32),
        },
    PluginAction = {
        ImageRectPosition = Vector2.new(384, 320),
        _Size = Vector2.new(32, 32),
        },
    PluginDebugService = {
        ImageRectPosition = Vector2.new(416, 320),
        _Size = Vector2.new(32, 32),
        },
    PluginDragEvent = {
        ImageRectPosition = Vector2.new(448, 320),
        _Size = Vector2.new(32, 32),
        },
    PluginGui = {
        ImageRectPosition = Vector2.new(480, 320),
        _Size = Vector2.new(32, 32),
        },
    PluginManagerInterface = {
        ImageRectPosition = Vector2.new(512, 320),
        _Size = Vector2.new(32, 32),
        },
    PluginMenu = {
        ImageRectPosition = Vector2.new(544, 320),
        _Size = Vector2.new(32, 32),
        },
    PluginToolbarButton = {
        ImageRectPosition = Vector2.new(576, 320),
        _Size = Vector2.new(32, 32),
        },
    Pose = {
        ImageRectPosition = Vector2.new(608, 320),
        _Size = Vector2.new(32, 32),
        },
    PoseBase = {
        ImageRectPosition = Vector2.new(640, 320),
        _Size = Vector2.new(32, 32),
        },
    PrismaticConstraint = {
        ImageRectPosition = Vector2.new(672, 320),
        _Size = Vector2.new(32, 32),
        },
    ProximityPrompt = {
        ImageRectPosition = Vector2.new(704, 320),
        _Size = Vector2.new(32, 32),
        },
    DataStoreKeyPages = {
        ImageRectPosition = Vector2.new(736, 320),
        _Size = Vector2.new(32, 32),
        },
    DataStoreObjectVersionInfo = {
        ImageRectPosition = Vector2.new(0, 352),
        _Size = Vector2.new(32, 32),
        },
    DataStoreOptions = {
        ImageRectPosition = Vector2.new(32, 352),
        _Size = Vector2.new(32, 32),
        },
    DebuggerBreakpoint = {
        ImageRectPosition = Vector2.new(64, 352),
        _Size = Vector2.new(32, 32),
        },
    DebuggerConnectionManager = {
        ImageRectPosition = Vector2.new(96, 352),
        _Size = Vector2.new(32, 32),
        },
    DebuggerVariable = {
        ImageRectPosition = Vector2.new(128, 352),
        _Size = Vector2.new(32, 32),
        },
    DebuggerWatch = {
        ImageRectPosition = Vector2.new(160, 352),
        _Size = Vector2.new(32, 32),
        },
    DebugSettings = {
        ImageRectPosition = Vector2.new(192, 352),
        _Size = Vector2.new(32, 32),
        },
    Dialog = {
        ImageRectPosition = Vector2.new(224, 352),
        _Size = Vector2.new(32, 32),
        },
    DialogChoice = {
        ImageRectPosition = Vector2.new(256, 352),
        _Size = Vector2.new(32, 32),
        },
    DistortionSoundEffect = {
        ImageRectPosition = Vector2.new(288, 352),
        _Size = Vector2.new(32, 32),
        },
    DraggerService = {
        ImageRectPosition = Vector2.new(320, 352),
        _Size = Vector2.new(32, 32),
        },
    EmotesPages = {
        ImageRectPosition = Vector2.new(352, 352),
        _Size = Vector2.new(32, 32),
        },
    EqualizerSoundEffect = {
        ImageRectPosition = Vector2.new(384, 352),
        _Size = Vector2.new(32, 32),
        },
    Explosion = {
        ImageRectPosition = Vector2.new(416, 352),
        _Size = Vector2.new(32, 32),
        },
    FaceAnimatorService = {
        ImageRectPosition = Vector2.new(448, 352),
        _Size = Vector2.new(32, 32),
        },
    FaceControls = {
        ImageRectPosition = Vector2.new(480, 352),
        _Size = Vector2.new(32, 32),
        },
    FacialAnimationRecordingService = {
        ImageRectPosition = Vector2.new(512, 352),
        _Size = Vector2.new(32, 32),
        },
    FlagStand = {
        ImageRectPosition = Vector2.new(544, 352),
        _Size = Vector2.new(32, 32),
        },
    FloorWire = {
        ImageRectPosition = Vector2.new(576, 352),
        _Size = Vector2.new(32, 32),
        },
    FormFactorPart = {
        ImageRectPosition = Vector2.new(608, 352),
        _Size = Vector2.new(32, 32),
        },
    FriendPages = {
        ImageRectPosition = Vector2.new(640, 352),
        _Size = Vector2.new(32, 32),
        },
    FunctionalTest = {
        ImageRectPosition = Vector2.new(672, 352),
        _Size = Vector2.new(32, 32),
        },
    GamepadService = {
        ImageRectPosition = Vector2.new(704, 352),
        _Size = Vector2.new(32, 32),
        },
    GamePassService = {
        ImageRectPosition = Vector2.new(736, 352),
        _Size = Vector2.new(32, 32),
        },
    GetTextBoundsParams = {
        ImageRectPosition = Vector2.new(0, 384),
        _Size = Vector2.new(32, 32),
        },
    GlobalSettings = {
        ImageRectPosition = Vector2.new(32, 384),
        _Size = Vector2.new(32, 32),
        },
    GoogleAnalyticsConfiguration = {
        ImageRectPosition = Vector2.new(64, 384),
        _Size = Vector2.new(32, 32),
        },
    GroundController = {
        ImageRectPosition = Vector2.new(96, 384),
        _Size = Vector2.new(32, 32),
        },
    GroupService = {
        ImageRectPosition = Vector2.new(128, 384),
        _Size = Vector2.new(32, 32),
        },
    GuiBase = {
        ImageRectPosition = Vector2.new(160, 384),
        _Size = Vector2.new(32, 32),
        },
    GuiBase2d = {
        ImageRectPosition = Vector2.new(192, 384),
        _Size = Vector2.new(32, 32),
        },
    GuiBase3d = {
        ImageRectPosition = Vector2.new(224, 384),
        _Size = Vector2.new(32, 32),
        },
    GuiButton = {
        ImageRectPosition = Vector2.new(256, 384),
        _Size = Vector2.new(32, 32),
        },
    GuiLabel = {
        ImageRectPosition = Vector2.new(288, 384),
        _Size = Vector2.new(32, 32),
        },
    GuiMain = {
        ImageRectPosition = Vector2.new(320, 384),
        _Size = Vector2.new(32, 32),
        },
    HandleAdornment = {
        ImageRectPosition = Vector2.new(352, 384),
        _Size = Vector2.new(32, 32),
        },
    Handles = {
        ImageRectPosition = Vector2.new(384, 384),
        _Size = Vector2.new(32, 32),
        },
    HapticService = {
        ImageRectPosition = Vector2.new(416, 384),
        _Size = Vector2.new(32, 32),
        },
    Hat = {
        ImageRectPosition = Vector2.new(448, 384),
        _Size = Vector2.new(32, 32),
        },
    HiddenSurfaceRemovalAsset = {
        ImageRectPosition = Vector2.new(480, 384),
        _Size = Vector2.new(32, 32),
        },
    Highlight = {
        ImageRectPosition = Vector2.new(512, 384),
        _Size = Vector2.new(32, 32),
        },
    HingeConstraint = {
        ImageRectPosition = Vector2.new(544, 384),
        _Size = Vector2.new(32, 32),
        },
    Hint = {
        ImageRectPosition = Vector2.new(576, 384),
        _Size = Vector2.new(32, 32),
        },
    Hole = {
        ImageRectPosition = Vector2.new(608, 384),
        _Size = Vector2.new(32, 32),
        },
    HttpRbxApiService = {
        ImageRectPosition = Vector2.new(640, 384),
        _Size = Vector2.new(32, 32),
        },
    HttpService = {
        ImageRectPosition = Vector2.new(672, 384),
        _Size = Vector2.new(32, 32),
        },
    Humanoid = {
        ImageRectPosition = Vector2.new(704, 384),
        _Size = Vector2.new(32, 32),
        },
    ILegacyStudioBridge = {
        ImageRectPosition = Vector2.new(736, 384),
        _Size = Vector2.new(32, 32),
        },
    ImporterAnimationSettings = {
        ImageRectPosition = Vector2.new(0, 416),
        _Size = Vector2.new(32, 32),
        },
    ImporterBaseSettings = {
        ImageRectPosition = Vector2.new(32, 416),
        _Size = Vector2.new(32, 32),
        },
    ImporterFacsSettings = {
        ImageRectPosition = Vector2.new(64, 416),
        _Size = Vector2.new(32, 32),
        },
    InputObject = {
        ImageRectPosition = Vector2.new(96, 416),
        _Size = Vector2.new(32, 32),
        },
    Instance = {
        ImageRectPosition = Vector2.new(128, 416),
        _Size = Vector2.new(32, 32),
        },
    IntConstrainedValue = {
        ImageRectPosition = Vector2.new(160, 416),
        _Size = Vector2.new(32, 32),
        },
    IntValue = {
        ImageRectPosition = Vector2.new(192, 416),
        _Size = Vector2.new(32, 32),
        },
    InventoryPages = {
        ImageRectPosition = Vector2.new(224, 416),
        _Size = Vector2.new(32, 32),
        },
    JointInstance = {
        ImageRectPosition = Vector2.new(256, 416),
        _Size = Vector2.new(32, 32),
        },
    Keyframe = {
        ImageRectPosition = Vector2.new(288, 416),
        _Size = Vector2.new(32, 32),
        },
    KeyframeMarker = {
        ImageRectPosition = Vector2.new(320, 416),
        _Size = Vector2.new(32, 32),
        },
    KeyframeSequenceProvider = {
        ImageRectPosition = Vector2.new(352, 416),
        _Size = Vector2.new(32, 32),
        },
    LegacyStudioBridge = {
        ImageRectPosition = Vector2.new(384, 416),
        _Size = Vector2.new(32, 32),
        },
    Light = {
        ImageRectPosition = Vector2.new(416, 416),
        _Size = Vector2.new(32, 32),
        },
    LineForce = {
        ImageRectPosition = Vector2.new(448, 416),
        _Size = Vector2.new(32, 32),
        },
    LocalDebuggerConnection = {
        ImageRectPosition = Vector2.new(480, 416),
        _Size = Vector2.new(32, 32),
        },
    LocalStorageService = {
        ImageRectPosition = Vector2.new(512, 416),
        _Size = Vector2.new(32, 32),
        },
    LodDataEntity = {
        ImageRectPosition = Vector2.new(544, 416),
        _Size = Vector2.new(32, 32),
        },
    LodDataService = {
        ImageRectPosition = Vector2.new(576, 416),
        _Size = Vector2.new(32, 32),
        },
    LoginService = {
        ImageRectPosition = Vector2.new(608, 416),
        _Size = Vector2.new(32, 32),
        },
    LogService = {
        ImageRectPosition = Vector2.new(640, 416),
        _Size = Vector2.new(32, 32),
        },
    LuaSettings = {
        ImageRectPosition = Vector2.new(672, 416),
        _Size = Vector2.new(32, 32),
        },
    LuaSourceContainer = {
        ImageRectPosition = Vector2.new(704, 416),
        _Size = Vector2.new(32, 32),
        },
    ManualGlue = {
        ImageRectPosition = Vector2.new(736, 416),
        _Size = Vector2.new(32, 32),
        },
    ManualSurfaceJointInstance = {
        ImageRectPosition = Vector2.new(0, 448),
        _Size = Vector2.new(32, 32),
        },
    MarketplaceService = {
        ImageRectPosition = Vector2.new(32, 448),
        _Size = Vector2.new(32, 32),
        },
    MaterialService = {
        ImageRectPosition = Vector2.new(64, 448),
        _Size = Vector2.new(32, 32),
        },
    MemoryStoreQueue = {
        ImageRectPosition = Vector2.new(96, 448),
        _Size = Vector2.new(32, 32),
        },
    MemoryStoreService = {
        ImageRectPosition = Vector2.new(128, 448),
        _Size = Vector2.new(32, 32),
        },
    MemoryStoreSortedMap = {
        ImageRectPosition = Vector2.new(160, 448),
        _Size = Vector2.new(32, 32),
        },
    MemStorageService = {
        ImageRectPosition = Vector2.new(192, 448),
        _Size = Vector2.new(32, 32),
        },
    MeshContentProvider = {
        ImageRectPosition = Vector2.new(224, 448),
        _Size = Vector2.new(32, 32),
        },
    MessageBusConnection = {
        ImageRectPosition = Vector2.new(256, 448),
        _Size = Vector2.new(32, 32),
        },
    MessageBusService = {
        ImageRectPosition = Vector2.new(288, 448),
        _Size = Vector2.new(32, 32),
        },
    MetaBreakpoint = {
        ImageRectPosition = Vector2.new(320, 448),
        _Size = Vector2.new(32, 32),
        },
    MetaBreakpointContext = {
        ImageRectPosition = Vector2.new(352, 448),
        _Size = Vector2.new(32, 32),
        },
    Model = {
        ImageRectPosition = Vector2.new(384, 448),
        _Size = Vector2.new(32, 32),
        },
    MouseService = {
        ImageRectPosition = Vector2.new(416, 448),
        _Size = Vector2.new(32, 32),
        },
    NetworkMarker = {
        ImageRectPosition = Vector2.new(448, 448),
        _Size = Vector2.new(32, 32),
        },
    NetworkReplicator = {
        ImageRectPosition = Vector2.new(480, 448),
        _Size = Vector2.new(32, 32),
        },
    NetworkServer = {
        ImageRectPosition = Vector2.new(512, 448),
        _Size = Vector2.new(32, 32),
        },
    ObjectValue = {
        ImageRectPosition = Vector2.new(544, 448),
        _Size = Vector2.new(32, 32),
        },
    PackageService = {
        ImageRectPosition = Vector2.new(576, 448),
        _Size = Vector2.new(32, 32),
        },
    Pages = {
        ImageRectPosition = Vector2.new(608, 448),
        _Size = Vector2.new(32, 32),
        },
    ParabolaAdornment = {
        ImageRectPosition = Vector2.new(640, 448),
        _Size = Vector2.new(32, 32),
        },
    Part = {
        ImageRectPosition = Vector2.new(672, 448),
        _Size = Vector2.new(32, 32),
        },
    PartAdornment = {
        ImageRectPosition = Vector2.new(704, 448),
        _Size = Vector2.new(32, 32),
        },
    PartOperationAsset = {
        ImageRectPosition = Vector2.new(736, 448),
        _Size = Vector2.new(32, 32),
        },
    Path = {
        ImageRectPosition = Vector2.new(0, 480),
        _Size = Vector2.new(32, 32),
        },
    PathfindingModifier = {
        ImageRectPosition = Vector2.new(32, 480),
        _Size = Vector2.new(32, 32),
        },
    PhysicsService = {
        ImageRectPosition = Vector2.new(64, 480),
        _Size = Vector2.new(32, 32),
        },
    PhysicsSettings = {
        ImageRectPosition = Vector2.new(96, 480),
        _Size = Vector2.new(32, 32),
        },
    PitchShiftSoundEffect = {
        ImageRectPosition = Vector2.new(128, 480),
        _Size = Vector2.new(32, 32),
        },
    Plane = {
        ImageRectPosition = Vector2.new(160, 480),
        _Size = Vector2.new(32, 32),
        },
    PlaneConstraint = {
        ImageRectPosition = Vector2.new(192, 480),
        _Size = Vector2.new(32, 32),
        },
    Platform = {
        ImageRectPosition = Vector2.new(224, 480),
        _Size = Vector2.new(32, 32),
        },
    Player = {
        ImageRectPosition = Vector2.new(256, 480),
        _Size = Vector2.new(32, 32),
        },
    PlayerEmulatorService = {
        ImageRectPosition = Vector2.new(288, 480),
        _Size = Vector2.new(32, 32),
        },
    PlayerGui = {
        ImageRectPosition = Vector2.new(320, 480),
        _Size = Vector2.new(32, 32),
        },
    PlayerMouse = {
        ImageRectPosition = Vector2.new(352, 480),
        _Size = Vector2.new(32, 32),
        },
    PluginGuiService = {
        ImageRectPosition = Vector2.new(384, 480),
        _Size = Vector2.new(32, 32),
        },
    PluginManagementService = {
        ImageRectPosition = Vector2.new(416, 480),
        _Size = Vector2.new(32, 32),
        },
    PluginManager = {
        ImageRectPosition = Vector2.new(448, 480),
        _Size = Vector2.new(32, 32),
        },
    PluginMouse = {
        ImageRectPosition = Vector2.new(480, 480),
        _Size = Vector2.new(32, 32),
        },
    PluginPolicyService = {
        ImageRectPosition = Vector2.new(512, 480),
        _Size = Vector2.new(32, 32),
        },
    PluginToolbar = {
        ImageRectPosition = Vector2.new(544, 480),
        _Size = Vector2.new(32, 32),
        },
    PointLight = {
        ImageRectPosition = Vector2.new(576, 480),
        _Size = Vector2.new(32, 32),
        },
    PointsService = {
        ImageRectPosition = Vector2.new(608, 480),
        _Size = Vector2.new(32, 32),
        },
    PolicyService = {
        ImageRectPosition = Vector2.new(640, 480),
        _Size = Vector2.new(32, 32),
        },
    PostEffect = {
        ImageRectPosition = Vector2.new(672, 480),
        _Size = Vector2.new(32, 32),
        },
    PVAdornment = {
        ImageRectPosition = Vector2.new(704, 480),
        _Size = Vector2.new(32, 32),
        },
    PVInstance = {
        ImageRectPosition = Vector2.new(736, 480),
        _Size = Vector2.new(32, 32),
        },
    RayValue = {
        ImageRectPosition = Vector2.new(0, 512),
        _Size = Vector2.new(32, 32),
        },
    RbxAnalyticsService = {
        ImageRectPosition = Vector2.new(32, 512),
        _Size = Vector2.new(32, 32),
        },
    ReflectionMetadata = {
        ImageRectPosition = Vector2.new(64, 512),
        _Size = Vector2.new(32, 32),
        },
    ReflectionMetadataCallbacks = {
        ImageRectPosition = Vector2.new(96, 512),
        _Size = Vector2.new(32, 32),
        },
    ReflectionMetadataEnum = {
        ImageRectPosition = Vector2.new(128, 512),
        _Size = Vector2.new(32, 32),
        },
    ReflectionMetadataEnums = {
        ImageRectPosition = Vector2.new(160, 512),
        _Size = Vector2.new(32, 32),
        },
    ReflectionMetadataEvents = {
        ImageRectPosition = Vector2.new(192, 512),
        _Size = Vector2.new(32, 32),
        },
    ReflectionMetadataItem = {
        ImageRectPosition = Vector2.new(224, 512),
        _Size = Vector2.new(32, 32),
        },
    ReflectionMetadataProperties = {
        ImageRectPosition = Vector2.new(256, 512),
        _Size = Vector2.new(32, 32),
        },
    RenderSettings = {
        ImageRectPosition = Vector2.new(288, 512),
        _Size = Vector2.new(32, 32),
        },
    ProcessInstancePhysicsService = {
        ImageRectPosition = Vector2.new(320, 512),
        _Size = Vector2.new(32, 32),
        },
    PublishService = {
        ImageRectPosition = Vector2.new(352, 512),
        _Size = Vector2.new(32, 32),
        },
    ReflectionMetadataClass = {
        ImageRectPosition = Vector2.new(384, 512),
        _Size = Vector2.new(32, 32),
        },
    ReflectionMetadataClasses = {
        ImageRectPosition = Vector2.new(416, 512),
        _Size = Vector2.new(32, 32),
        },
    ReflectionMetadataEnumItem = {
        ImageRectPosition = Vector2.new(448, 512),
        _Size = Vector2.new(32, 32),
        },
    ReflectionMetadataFunctions = {
        ImageRectPosition = Vector2.new(480, 512),
        _Size = Vector2.new(32, 32),
        },
    RemoteFunction = {
        ImageRectPosition = Vector2.new(512, 512),
        _Size = Vector2.new(32, 32),
        },
    ReplicatedStorage = {
        ImageRectPosition = Vector2.new(544, 512),
        _Size = Vector2.new(32, 32),
        },
    RobloxReplicatedStorage = {
        ImageRectPosition = Vector2.new(576, 512),
        _Size = Vector2.new(32, 32),
        },
    RotateP = {
        ImageRectPosition = Vector2.new(608, 512),
        _Size = Vector2.new(32, 32),
        },
    RtMessagingService = {
        ImageRectPosition = Vector2.new(640, 512),
        _Size = Vector2.new(32, 32),
        },
    ScreenshotHud = {
        ImageRectPosition = Vector2.new(672, 512),
        _Size = Vector2.new(32, 32),
        },
    ScriptChangeService = {
        ImageRectPosition = Vector2.new(704, 512),
        _Size = Vector2.new(32, 32),
        },
    ScriptCloneWatcher = {
        ImageRectPosition = Vector2.new(736, 512),
        _Size = Vector2.new(32, 32),
        },
    Seat = {
        ImageRectPosition = Vector2.new(0, 544),
        _Size = Vector2.new(32, 32),
        },
    SelectionLasso = {
        ImageRectPosition = Vector2.new(32, 544),
        _Size = Vector2.new(32, 32),
        },
    SelectionPointLasso = {
        ImageRectPosition = Vector2.new(64, 544),
        _Size = Vector2.new(32, 32),
        },
    ServerStorage = {
        ImageRectPosition = Vector2.new(96, 544),
        _Size = Vector2.new(32, 32),
        },
    SkateboardPlatform = {
        ImageRectPosition = Vector2.new(128, 544),
        _Size = Vector2.new(32, 32),
        },
    Sky = {
        ImageRectPosition = Vector2.new(160, 544),
        _Size = Vector2.new(32, 32),
        },
    SoundEffect = {
        ImageRectPosition = Vector2.new(192, 544),
        _Size = Vector2.new(32, 32),
        },
    SpawnLocation = {
        ImageRectPosition = Vector2.new(224, 544),
        _Size = Vector2.new(32, 32),
        },
    Speaker = {
        ImageRectPosition = Vector2.new(256, 544),
        _Size = Vector2.new(32, 32),
        },
    StackFrame = {
        ImageRectPosition = Vector2.new(288, 544),
        _Size = Vector2.new(32, 32),
        },
    StarterGear = {
        ImageRectPosition = Vector2.new(320, 544),
        _Size = Vector2.new(32, 32),
        },
    StarterPack = {
        ImageRectPosition = Vector2.new(352, 544),
        _Size = Vector2.new(32, 32),
        },
    Stats = {
        ImageRectPosition = Vector2.new(384, 544),
        _Size = Vector2.new(32, 32),
        },
    Status = {
        ImageRectPosition = Vector2.new(416, 544),
        _Size = Vector2.new(32, 32),
        },
    StopWatchReporter = {
        ImageRectPosition = Vector2.new(448, 544),
        _Size = Vector2.new(32, 32),
        },
    StudioAssetService = {
        ImageRectPosition = Vector2.new(480, 544),
        _Size = Vector2.new(32, 32),
        },
    StudioHighDpiService = {
        ImageRectPosition = Vector2.new(512, 544),
        _Size = Vector2.new(32, 32),
        },
    SurfaceGui = {
        ImageRectPosition = Vector2.new(544, 544),
        _Size = Vector2.new(32, 32),
        },
    TeamCreateService = {
        ImageRectPosition = Vector2.new(576, 544),
        _Size = Vector2.new(32, 32),
        },
    TemporaryCageMeshProvider = {
        ImageRectPosition = Vector2.new(608, 544),
        _Size = Vector2.new(32, 32),
        },
    TerrainRegion = {
        ImageRectPosition = Vector2.new(640, 544),
        _Size = Vector2.new(32, 32),
        },
    TextBoxService = {
        ImageRectPosition = Vector2.new(672, 544),
        _Size = Vector2.new(32, 32),
        },
    TextChannel = {
        ImageRectPosition = Vector2.new(704, 544),
        _Size = Vector2.new(32, 32),
        },
    TextChatConfigurations = {
        ImageRectPosition = Vector2.new(736, 544),
        _Size = Vector2.new(32, 32),
        },
    TextChatMessage = {
        ImageRectPosition = Vector2.new(0, 576),
        _Size = Vector2.new(32, 32),
        },
    TextLabel = {
        ImageRectPosition = Vector2.new(32, 576),
        _Size = Vector2.new(32, 32),
        },
    TextService = {
        ImageRectPosition = Vector2.new(64, 576),
        _Size = Vector2.new(32, 32),
        },
    ThirdPartyUserService = {
        ImageRectPosition = Vector2.new(96, 576),
        _Size = Vector2.new(32, 32),
        },
    ThreadState = {
        ImageRectPosition = Vector2.new(128, 576),
        _Size = Vector2.new(32, 32),
        },
    ToastNotificationService = {
        ImageRectPosition = Vector2.new(160, 576),
        _Size = Vector2.new(32, 32),
        },
    ToolboxService = {
        ImageRectPosition = Vector2.new(192, 576),
        _Size = Vector2.new(32, 32),
        },
    Torque = {
        ImageRectPosition = Vector2.new(224, 576),
        _Size = Vector2.new(32, 32),
        },
    TorsionSpringConstraint = {
        ImageRectPosition = Vector2.new(256, 576),
        _Size = Vector2.new(32, 32),
        },
    UIAspectRatioConstraint = {
        ImageRectPosition = Vector2.new(288, 576),
        _Size = Vector2.new(32, 32),
        },
    UICorner = {
        ImageRectPosition = Vector2.new(320, 576),
        _Size = Vector2.new(32, 32),
        },
    UIScale = {
        ImageRectPosition = Vector2.new(352, 576),
        _Size = Vector2.new(32, 32),
        },
    UISizeConstraint = {
        ImageRectPosition = Vector2.new(384, 576),
        _Size = Vector2.new(32, 32),
        },
    UnvalidatedAssetService = {
        ImageRectPosition = Vector2.new(416, 576),
        _Size = Vector2.new(32, 32),
        },
    UserService = {
        ImageRectPosition = Vector2.new(448, 576),
        _Size = Vector2.new(32, 32),
        },
    UserSettings = {
        ImageRectPosition = Vector2.new(480, 576),
        _Size = Vector2.new(32, 32),
        },
    VectorForce = {
        ImageRectPosition = Vector2.new(512, 576),
        _Size = Vector2.new(32, 32),
        },
    VehicleController = {
        ImageRectPosition = Vector2.new(544, 576),
        _Size = Vector2.new(32, 32),
        },
    Visit = {
        ImageRectPosition = Vector2.new(576, 576),
        _Size = Vector2.new(32, 32),
        },
    VoiceChatInternal = {
        ImageRectPosition = Vector2.new(608, 576),
        _Size = Vector2.new(32, 32),
        },
    VoiceChatService = {
        ImageRectPosition = Vector2.new(640, 576),
        _Size = Vector2.new(32, 32),
        },
    VRService = {
        ImageRectPosition = Vector2.new(672, 576),
        _Size = Vector2.new(32, 32),
        },
    WireframeHandleAdornment = {
        ImageRectPosition = Vector2.new(704, 576),
        _Size = Vector2.new(32, 32),
        },
    ReflectionMetadataYieldFunctions = {
        ImageRectPosition = Vector2.new(736, 576),
        _Size = Vector2.new(32, 32),
        },
    ReverbSoundEffect = {
        ImageRectPosition = Vector2.new(0, 608),
        _Size = Vector2.new(32, 32),
        },
    RobloxPluginGuiService = {
        ImageRectPosition = Vector2.new(32, 608),
        _Size = Vector2.new(32, 32),
        },
    RocketPropulsion = {
        ImageRectPosition = Vector2.new(64, 608),
        _Size = Vector2.new(32, 32),
        },
    RunService = {
        ImageRectPosition = Vector2.new(96, 608),
        _Size = Vector2.new(32, 32),
        },
    ScriptDebugger = {
        ImageRectPosition = Vector2.new(128, 608),
        _Size = Vector2.new(32, 32),
        },
    ScriptDocument = {
        ImageRectPosition = Vector2.new(160, 608),
        _Size = Vector2.new(32, 32),
        },
    ScriptEditorService = {
        ImageRectPosition = Vector2.new(192, 608),
        _Size = Vector2.new(32, 32),
        },
    ScriptService = {
        ImageRectPosition = Vector2.new(224, 608),
        _Size = Vector2.new(32, 32),
        },
    ScrollingFrame = {
        ImageRectPosition = Vector2.new(256, 608),
        _Size = Vector2.new(32, 32),
        },
    Selection = {
        ImageRectPosition = Vector2.new(288, 608),
        _Size = Vector2.new(32, 32),
        },
    ServiceProvider = {
        ImageRectPosition = Vector2.new(320, 608),
        _Size = Vector2.new(32, 32),
        },
    SoundGroup = {
        ImageRectPosition = Vector2.new(352, 608),
        _Size = Vector2.new(32, 32),
        },
    SoundService = {
        ImageRectPosition = Vector2.new(384, 608),
        _Size = Vector2.new(32, 32),
        },
    StarterPlayer = {
        ImageRectPosition = Vector2.new(416, 608),
        _Size = Vector2.new(32, 32),
        },
    SurfaceGuiBase = {
        ImageRectPosition = Vector2.new(448, 608),
        _Size = Vector2.new(32, 32),
        },
    SurfaceLight = {
        ImageRectPosition = Vector2.new(480, 608),
        _Size = Vector2.new(32, 32),
        },
    Team = {
        ImageRectPosition = Vector2.new(512, 608),
        _Size = Vector2.new(32, 32),
        },
    Teams = {
        ImageRectPosition = Vector2.new(544, 608),
        _Size = Vector2.new(32, 32),
        },
    TeleportOptions = {
        ImageRectPosition = Vector2.new(576, 608),
        _Size = Vector2.new(32, 32),
        },
    TeleportService = {
        ImageRectPosition = Vector2.new(608, 608),
        _Size = Vector2.new(32, 32),
        },
    Terrain = {
        ImageRectPosition = Vector2.new(640, 608),
        _Size = Vector2.new(32, 32),
        },
    TerrainDetail = {
        ImageRectPosition = Vector2.new(672, 608),
        _Size = Vector2.new(32, 32),
        },
    TextButton = {
        ImageRectPosition = Vector2.new(704, 608),
        _Size = Vector2.new(32, 32),
        },
    TextChatMessageProperties = {
        ImageRectPosition = Vector2.new(736, 608),
        _Size = Vector2.new(32, 32),
        },
    TextChatService = {
        ImageRectPosition = Vector2.new(0, 640),
        _Size = Vector2.new(32, 32),
        },
    TimerService = {
        ImageRectPosition = Vector2.new(32, 640),
        _Size = Vector2.new(32, 32),
        },
    TouchInputService = {
        ImageRectPosition = Vector2.new(64, 640),
        _Size = Vector2.new(32, 32),
        },
    TracerService = {
        ImageRectPosition = Vector2.new(96, 640),
        _Size = Vector2.new(32, 32),
        },
    TrackerStreamAnimation = {
        ImageRectPosition = Vector2.new(128, 640),
        _Size = Vector2.new(32, 32),
        },
    Translator = {
        ImageRectPosition = Vector2.new(160, 640),
        _Size = Vector2.new(32, 32),
        },
    TweenBase = {
        ImageRectPosition = Vector2.new(192, 640),
        _Size = Vector2.new(32, 32),
        },
    TweenService = {
        ImageRectPosition = Vector2.new(224, 640),
        _Size = Vector2.new(32, 32),
        },
    UIGradient = {
        ImageRectPosition = Vector2.new(256, 640),
        _Size = Vector2.new(32, 32),
        },
    UIGridStyleLayout = {
        ImageRectPosition = Vector2.new(288, 640),
        _Size = Vector2.new(32, 32),
        },
    UIListLayout = {
        ImageRectPosition = Vector2.new(320, 640),
        _Size = Vector2.new(32, 32),
        },
    UIPageLayout = {
        ImageRectPosition = Vector2.new(352, 640),
        _Size = Vector2.new(32, 32),
        },
    UITableLayout = {
        ImageRectPosition = Vector2.new(384, 640),
        _Size = Vector2.new(32, 32),
        },
    VehicleSeat = {
        ImageRectPosition = Vector2.new(416, 640),
        _Size = Vector2.new(32, 32),
        },
    VelocityMotor = {
        ImageRectPosition = Vector2.new(448, 640),
        _Size = Vector2.new(32, 32),
        },
    WedgePart = {
        ImageRectPosition = Vector2.new(480, 640),
        _Size = Vector2.new(32, 32),
        },
    Weld = {
        ImageRectPosition = Vector2.new(512, 640),
        _Size = Vector2.new(32, 32),
        },
    WorldModel = {
        ImageRectPosition = Vector2.new(544, 640),
        _Size = Vector2.new(32, 32),
        },
    WorldRoot = {
        ImageRectPosition = Vector2.new(576, 640),
        _Size = Vector2.new(32, 32),
        },
    WrapLayer = {
        ImageRectPosition = Vector2.new(608, 640),
        _Size = Vector2.new(32, 32),
        },
    WrapTarget = {
        ImageRectPosition = Vector2.new(640, 640),
        _Size = Vector2.new(32, 32),
        },
    ProximityPromptService = {
        ImageRectPosition = Vector2.new(672, 640),
        _Size = Vector2.new(32, 32),
        },
    QWidgetPluginGui = {
        ImageRectPosition = Vector2.new(704, 640),
        _Size = Vector2.new(32, 32),
        },
    ReflectionMetadataMember = {
        ImageRectPosition = Vector2.new(736, 640),
        _Size = Vector2.new(32, 32),
        },
    RemoteDebuggerServer = {
        ImageRectPosition = Vector2.new(0, 672),
        _Size = Vector2.new(32, 32),
        },
    RemoteEvent = {
        ImageRectPosition = Vector2.new(32, 672),
        _Size = Vector2.new(32, 32),
        },
    RenderingTest = {
        ImageRectPosition = Vector2.new(64, 672),
        _Size = Vector2.new(32, 32),
        },
    ReplicatedFirst = {
        ImageRectPosition = Vector2.new(96, 672),
        _Size = Vector2.new(32, 32),
        },
    Rotate = {
        ImageRectPosition = Vector2.new(128, 672),
        _Size = Vector2.new(32, 32),
        },
    RotationCurve = {
        ImageRectPosition = Vector2.new(160, 672),
        _Size = Vector2.new(32, 32),
        },
    RunningAverageItemDouble = {
        ImageRectPosition = Vector2.new(192, 672),
        _Size = Vector2.new(32, 32),
        },
    RuntimeScriptService = {
        ImageRectPosition = Vector2.new(224, 672),
        _Size = Vector2.new(32, 32),
        },
    ScreenGui = {
        ImageRectPosition = Vector2.new(256, 672),
        _Size = Vector2.new(32, 32),
        },
    Script = {
        ImageRectPosition = Vector2.new(288, 672),
        _Size = Vector2.new(32, 32),
        },
    SelectionBox = {
        ImageRectPosition = Vector2.new(320, 672),
        _Size = Vector2.new(32, 32),
        },
    SlidingBallConstraint = {
        ImageRectPosition = Vector2.new(352, 672),
        _Size = Vector2.new(32, 32),
        },
    Smoke = {
        ImageRectPosition = Vector2.new(384, 672),
        _Size = Vector2.new(32, 32),
        },
    Snap = {
        ImageRectPosition = Vector2.new(416, 672),
        _Size = Vector2.new(32, 32),
        },
    SnippetService = {
        ImageRectPosition = Vector2.new(448, 672),
        _Size = Vector2.new(32, 32),
        },
    SolidModelContentProvider = {
        ImageRectPosition = Vector2.new(480, 672),
        _Size = Vector2.new(32, 32),
        },
    Sparkles = {
        ImageRectPosition = Vector2.new(512, 672),
        _Size = Vector2.new(32, 32),
        },
    SpawnerService = {
        ImageRectPosition = Vector2.new(544, 672),
        _Size = Vector2.new(32, 32),
        },
    SpecialMesh = {
        ImageRectPosition = Vector2.new(576, 672),
        _Size = Vector2.new(32, 32),
        },
    SpringConstraint = {
        ImageRectPosition = Vector2.new(608, 672),
        _Size = Vector2.new(32, 32),
        },
    StandalonePluginScripts = {
        ImageRectPosition = Vector2.new(640, 672),
        _Size = Vector2.new(32, 32),
        },
    StandardPages = {
        ImageRectPosition = Vector2.new(672, 672),
        _Size = Vector2.new(32, 32),
        },
    StarterCharacterScripts = {
        ImageRectPosition = Vector2.new(704, 672),
        _Size = Vector2.new(32, 32),
        },
    StatsItem = {
        ImageRectPosition = Vector2.new(736, 672),
        _Size = Vector2.new(32, 32),
        },
    StudioPublishService = {
        ImageRectPosition = Vector2.new(0, 704),
        _Size = Vector2.new(32, 32),
        },
    SurfaceAppearance = {
        ImageRectPosition = Vector2.new(32, 704),
        _Size = Vector2.new(32, 32),
        },
    SwimController = {
        ImageRectPosition = Vector2.new(64, 704),
        _Size = Vector2.new(32, 32),
        },
    TaskScheduler = {
        ImageRectPosition = Vector2.new(96, 704),
        _Size = Vector2.new(32, 32),
        },
    TeleportAsyncResult = {
        ImageRectPosition = Vector2.new(128, 704),
        _Size = Vector2.new(32, 32),
        },
    TestService = {
        ImageRectPosition = Vector2.new(160, 704),
        _Size = Vector2.new(32, 32),
        },
    TextSource = {
        ImageRectPosition = Vector2.new(192, 704),
        _Size = Vector2.new(32, 32),
        },
    Tool = {
        ImageRectPosition = Vector2.new(224, 704),
        _Size = Vector2.new(32, 32),
        },
    TotalCountTimeIntervalItem = {
        ImageRectPosition = Vector2.new(256, 704),
        _Size = Vector2.new(32, 32),
        },
    TouchTransmitter = {
        ImageRectPosition = Vector2.new(288, 704),
        _Size = Vector2.new(32, 32),
        },
    Trail = {
        ImageRectPosition = Vector2.new(320, 704),
        _Size = Vector2.new(32, 32),
        },
    TremoloSoundEffect = {
        ImageRectPosition = Vector2.new(352, 704),
        _Size = Vector2.new(32, 32),
        },
    UIBase = {
        ImageRectPosition = Vector2.new(384, 704),
        _Size = Vector2.new(32, 32),
        },
    UIStroke = {
        ImageRectPosition = Vector2.new(416, 704),
        _Size = Vector2.new(32, 32),
        },
    UniversalConstraint = {
        ImageRectPosition = Vector2.new(448, 704),
        _Size = Vector2.new(32, 32),
        },
    UserGameSettings = {
        ImageRectPosition = Vector2.new(480, 704),
        _Size = Vector2.new(32, 32),
        },
    UserInputService = {
        ImageRectPosition = Vector2.new(512, 704),
        _Size = Vector2.new(32, 32),
        },
    ValueBase = {
        ImageRectPosition = Vector2.new(544, 704),
        _Size = Vector2.new(32, 32),
        },
    VersionControlService = {
        ImageRectPosition = Vector2.new(576, 704),
        _Size = Vector2.new(32, 32),
        },
    VideoCaptureService = {
        ImageRectPosition = Vector2.new(608, 704),
        _Size = Vector2.new(32, 32),
        },
    VirtualInputManager = {
        ImageRectPosition = Vector2.new(640, 704),
        _Size = Vector2.new(32, 32),
        },
    VirtualUser = {
        ImageRectPosition = Vector2.new(672, 704),
        _Size = Vector2.new(32, 32),
        },
    VisibilityService = {
        ImageRectPosition = Vector2.new(704, 704),
        _Size = Vector2.new(32, 32),
        },
    VoiceChannel = {
        ImageRectPosition = Vector2.new(736, 704),
        _Size = Vector2.new(32, 32),
        },
    VoiceSource = {
        ImageRectPosition = Vector2.new(0, 736),
        _Size = Vector2.new(32, 32),
        },
    RigidConstraint = {
        ImageRectPosition = Vector2.new(32, 736),
        _Size = Vector2.new(32, 32),
        },
    RodConstraint = {
        ImageRectPosition = Vector2.new(64, 736),
        _Size = Vector2.new(32, 32),
        },
    RopeConstraint = {
        ImageRectPosition = Vector2.new(96, 736),
        _Size = Vector2.new(32, 32),
        },
    RotateV = {
        ImageRectPosition = Vector2.new(128, 736),
        _Size = Vector2.new(32, 32),
        },
    RunningAverageItemInt = {
        ImageRectPosition = Vector2.new(160, 736),
        _Size = Vector2.new(32, 32),
        },
    RunningAverageTimeIntervalItem = {
        ImageRectPosition = Vector2.new(192, 736),
        _Size = Vector2.new(32, 32),
        },
    ScriptCloneWatcherHelper = {
        ImageRectPosition = Vector2.new(224, 736),
        _Size = Vector2.new(32, 32),
        },
    ScriptContext = {
        ImageRectPosition = Vector2.new(256, 736),
        _Size = Vector2.new(32, 32),
        },
    ScriptRegistrationService = {
        ImageRectPosition = Vector2.new(288, 736),
        _Size = Vector2.new(32, 32),
        },
    SelectionPartLasso = {
        ImageRectPosition = Vector2.new(320, 736),
        _Size = Vector2.new(32, 32),
        },
    SelectionSphere = {
        ImageRectPosition = Vector2.new(352, 736),
        _Size = Vector2.new(32, 32),
        },
    ServerReplicator = {
        ImageRectPosition = Vector2.new(384, 736),
        _Size = Vector2.new(32, 32),
        },
    ServerScriptService = {
        ImageRectPosition = Vector2.new(416, 736),
        _Size = Vector2.new(32, 32),
        },
    SessionService = {
        ImageRectPosition = Vector2.new(448, 736),
        _Size = Vector2.new(32, 32),
        },
    Shirt = {
        ImageRectPosition = Vector2.new(480, 736),
        _Size = Vector2.new(32, 32),
        },
    ShirtGraphic = {
        ImageRectPosition = Vector2.new(512, 736),
        _Size = Vector2.new(32, 32),
        },
    SkateboardController = {
        ImageRectPosition = Vector2.new(544, 736),
        _Size = Vector2.new(32, 32),
        },
    Skin = {
        ImageRectPosition = Vector2.new(576, 736),
        _Size = Vector2.new(32, 32),
        },
    SocialService = {
        ImageRectPosition = Vector2.new(608, 736),
        _Size = Vector2.new(32, 32),
        },
    Sound = {
        ImageRectPosition = Vector2.new(640, 736),
        _Size = Vector2.new(32, 32),
        },
    SphereHandleAdornment = {
        ImageRectPosition = Vector2.new(672, 736),
        _Size = Vector2.new(32, 32),
        },
    SpotLight = {
        ImageRectPosition = Vector2.new(704, 736),
        _Size = Vector2.new(32, 32),
        },
    StarterGui = {
        ImageRectPosition = Vector2.new(736, 736),
        _Size = Vector2.new(32, 32),
        },
    StarterPlayerScripts = {
        ImageRectPosition = Vector2.new(0, 768),
        _Size = Vector2.new(32, 32),
        },
    StringValue = {
        ImageRectPosition = Vector2.new(32, 768),
        _Size = Vector2.new(32, 32),
        },
    Studio = {
        ImageRectPosition = Vector2.new(64, 768),
        _Size = Vector2.new(32, 32),
        },
    StudioData = {
        ImageRectPosition = Vector2.new(96, 768),
        _Size = Vector2.new(32, 32),
        },
    StudioDeviceEmulatorService = {
        ImageRectPosition = Vector2.new(128, 768),
        _Size = Vector2.new(32, 32),
        },
    StudioScriptDebugEventListener = {
        ImageRectPosition = Vector2.new(160, 768),
        _Size = Vector2.new(32, 32),
        },
    StudioService = {
        ImageRectPosition = Vector2.new(192, 768),
        _Size = Vector2.new(32, 32),
        },
    StudioTheme = {
        ImageRectPosition = Vector2.new(224, 768),
        _Size = Vector2.new(32, 32),
        },
    SunRaysEffect = {
        ImageRectPosition = Vector2.new(256, 768),
        _Size = Vector2.new(32, 32),
        },
    SurfaceSelection = {
        ImageRectPosition = Vector2.new(288, 768),
        _Size = Vector2.new(32, 32),
        },
    TemporaryScriptService = {
        ImageRectPosition = Vector2.new(320, 768),
        _Size = Vector2.new(32, 32),
        },
    TextBox = {
        ImageRectPosition = Vector2.new(352, 768),
        _Size = Vector2.new(32, 32),
        },
    TextChatCommand = {
        ImageRectPosition = Vector2.new(384, 768),
        _Size = Vector2.new(32, 32),
        },
    TextFilterResult = {
        ImageRectPosition = Vector2.new(416, 768),
        _Size = Vector2.new(32, 32),
        },
    Texture = {
        ImageRectPosition = Vector2.new(448, 768),
        _Size = Vector2.new(32, 32),
        },
    TriangleMeshPart = {
        ImageRectPosition = Vector2.new(480, 768),
        _Size = Vector2.new(32, 32),
        },
    TrussPart = {
        ImageRectPosition = Vector2.new(512, 768),
        _Size = Vector2.new(32, 32),
        },
    Tween = {
        ImageRectPosition = Vector2.new(544, 768),
        _Size = Vector2.new(32, 32),
        },
    UGCValidationService = {
        ImageRectPosition = Vector2.new(576, 768),
        _Size = Vector2.new(32, 32),
        },
    UIComponent = {
        ImageRectPosition = Vector2.new(608, 768),
        _Size = Vector2.new(32, 32),
        },
    UIConstraint = {
        ImageRectPosition = Vector2.new(640, 768),
        _Size = Vector2.new(32, 32),
        },
    UIGridLayout = {
        ImageRectPosition = Vector2.new(672, 768),
        _Size = Vector2.new(32, 32),
        },
    UILayout = {
        ImageRectPosition = Vector2.new(704, 768),
        _Size = Vector2.new(32, 32),
        },
    UIPadding = {
        ImageRectPosition = Vector2.new(736, 768),
        _Size = Vector2.new(32, 32),
        },
    UITextSizeConstraint = {
        ImageRectPosition = Vector2.new(0, 800),
        _Size = Vector2.new(32, 32),
        },
    UnionOperation = {
        ImageRectPosition = Vector2.new(32, 800),
        _Size = Vector2.new(32, 32),
        },
    UserStorageService = {
        ImageRectPosition = Vector2.new(64, 800),
        _Size = Vector2.new(32, 32),
        },
    Vector3Curve = {
        ImageRectPosition = Vector2.new(96, 800),
        _Size = Vector2.new(32, 32),
        },
    Vector3Value = {
        ImageRectPosition = Vector2.new(128, 800),
        _Size = Vector2.new(32, 32),
        },
    VideoFrame = {
        ImageRectPosition = Vector2.new(160, 800),
        _Size = Vector2.new(32, 32),
        },
    ViewportFrame = {
        ImageRectPosition = Vector2.new(192, 800),
        _Size = Vector2.new(32, 32),
        },
    WeldConstraint = {
        ImageRectPosition = Vector2.new(224, 800),
        _Size = Vector2.new(32, 32),
        },
    Workspace = {
        ImageRectPosition = Vector2.new(256, 800),
        _Size = Vector2.new(32, 32),
        },
}
return icons
    